### ISSUE TITLE
Refactoring WHERE clause.

### ISSUE THREAD

**Issue by kugimiya** [kugimiya/brodieja#2]
In `brodieja/app/lib/db_query.php` we need refactoring.

So, in ideal case:
```
    ->where('id', 25, '>')
    ->and()
    ->where('id', 45, '<')
    ->and()
    ->where('name', 'Dimon');

// WHERE (( 'id' > 25 ) AND ( 'id' < 45 ) AND ( 'name' = 'Dimon' ))
```

**Comment by kugimiya** [comment]
Yep.

**Comment by ridouchire** [comment]
Лол, наканецта

**Comment by kugimiya** [comment]
Когда привык писать `->where('col', '=', 25);` а теперь второй стул с `->whereEqual(['col' => 25]);`

**Comment by ridouchire** [comment]
Сука, сидеть и коммитить ишью веселее, чем скроллить сосачи же!
