### ISSUE TITLE
ну че как дела

### ISSUE THREAD

**Issue by Sierss** [kugimiya/brodieja#29]
Андрей, если это ты. Заебал, как маленький, скинь мне выгрузку БД по мясу. До меня дошли какие-то ебанутые новости о тебе, но блять ты комитишь тут

**Comment by Xenus-Ghost** [comment]
Чево блять, какое мясо, тут CMS для сайтов

**Comment by ridouchire** [comment]
Да лан те, пусть коммитит. Недолго пацану осталось...

**Comment by ridouchire** [comment]
А можно посмотреть ваш проект сайта скотобойни, как я понял? Вдруг я смогу скинуть мясо.

**Comment by Sierss** [comment]
адресовано @kugimiya 
Вообще кто нибудь знает где он ?

**Comment by ridouchire** [comment]
Уже три месяца парень на связь не выходит, раньше в чате общались и общие проекты делали.

**Comment by Xenus-Ghost** [comment]
@Sierss а ты где?

**Comment by ridouchire** [comment]
А что случилось? Почему вы создаёте ишью по нерелевантной проблеме проекта?

**Comment by vladd12** [comment]
Че пацаны ониме?

**Comment by Sierss** [comment]
Тоже проект делали, он исчез месяц назад, удалился везде. Зашел на гит, смотрю он коммитил тут, не заметил вас в участниках. Тогда вопрос закрыт.

**Comment by Sierss** [comment]
Если он отдал кому то из вас акк, то понятно, если же нет, встает вопрос, кто это?

**Comment by Sierss** [comment]
@ridouchire Буду благодарен если прокомментируете эту ситуацию.

**Comment by kugimiya** [comment]
что за хуйня в репозитории юме на аккаунте юме?
юме это не та страна, которая выдает борцов за свободу крокодила
и вообще оратор выше все сказал
>Чево блять, какое мясо, тут CMS для сайтов

**Comment by vladd12** [comment]
ну-ну репозитории хуезитории нуну

**Comment by ridouchire** [comment]
Хорошо сказал, хорошо закрыл.
